### ISSUE TITLE
Use full path in generated CSS

### ISSUE THREAD

**Issue by RoelN** [Wakamai-Fondue/wakamai-fondue-cli#12]
E.g.

```sh
$ wakamai-fondue -c ~/Desktop/Fonts/Milkshake.otf
```

currently uses only the filename in the output:

```css
/**
 * CSS for Milkshake
 * Generated by Wakamai Fondue - https://wakamaifondue.com
 * by Roel Nieskens/PixelAmbacht - https://pixelambacht.nl
 */

@font-face {
    font-family: "Milkshake";
    src: url("Milkshake.otf");
    ...
}
```
